### ISSUE TITLE
covert yolov3-spp.cfg to onnx,reporting TypeError: buffer is too small for requested array

### ISSUE THREAD

**Issue by tomtomkite** [Cw-zero/TensorRT_yolo3#3]
Hi，
When I was trying to covert yolov3-spp model to onnx, I got the error at  "buffer=self.weights_file.read(param_size * 4))" at the end of function of "def _load_one_param_type(self, conv_params, param_category, suffix)"

I use python2.7, and test the code on GTX2080TI,with cuda-10 and tensorrt 5.

have you ever meet this issue?

**Comment by Cw-zero** [comment]
I am sorry that I do not test yolov3-spp model, but I know that yolov3-spp.cfg is different from yolo3.cfg. yolov3-spp.cfg has more [convolutional] and [maxpool], so you may need to change the code.

**Comment by tangsipeng** [comment]
> 
> 
> Hi，
> When I was trying to covert yolov3-spp model to onnx, I got the error at "buffer=self.weights_file.read(param_size * 4))" at the end of function of "def _load_one_param_type(self, conv_params, param_category, suffix)"
> 
> I use python2.7, and test the code on GTX2080TI,with cuda-10 and tensorrt 5.
> 
> have you ever meet this issue?

i met the same problem 
i change the code and get the onnx model , but i cannot change onnx to trt model .it always get the 'shape of concat ' problem.

**Comment by liguoyu666** [comment]
> > Hi，
> > When I was trying to covert yolov3-spp model to onnx, I got the error at "buffer=self.weights_file.read(param_size * 4))" at the end of function of "def _load_one_param_type(self, conv_params, param_category, suffix)"
> > I use python2.7, and test the code on GTX2080TI,with cuda-10 and tensorrt 5.
> > have you ever meet this issue?
> 
> i met the same problem
> i change the code and get the onnx model , but i cannot change onnx to trt model .it always get the 'shape of concat ' problem.

HI, I met the same problem, have you solved it ?
