### ISSUE TITLE
请教一下关于Upsample问题

### ISSUE THREAD

**Issue by MenGuangwen-CN-0411** [Cw-zero/TensorRT_yolo3#4]
你好，使用你的这个工程的方式helper.make_node(
'Upsample',
mode='nearest',
scales=[1.0, 1.0, 2, 2],
inputs=inputs,
outputs=[layer_name],
name=layer_name,
)
可以得到
onnx::Upsample[mode = 'nearest', scales = [1, 1, 2, 2]]....
但是如果使用：nn.Upsample(scale_factor=2, mode = 'nearest'),这种方式，之后用torch.onnx.export导出方式，只能得到：
onnx::Upsample[mode="nearest"].....
我该如何用导出方式得到还有 scales 属性的onnx::Upsample呢？

**Comment by xiaoxifuhongse** [comment]
I have a problem like this: 
onnx.onnx_cpp2py_export.checker.ValidationError: Op registered for Upsample is depracted in domain_version of 10
==> Context: Bad node spec: input: "085_convolutional_lrelu" output: "086_upsample" name: "086_upsample" op_type: "Upsample" attribute { name: "mode" s: "nearest" type: STRING } attribute { name: "scales" floats: 1 floats: 1 floats: 2 floats: 2 type: FLOATS }
